### ISSUE TITLE
Wrong return type for Project getters

### ISSUE THREAD

**Issue by mingushead** [weaverplatform/weaver-sdk-js#82]
`weaver.currentProject()` and `Weaver.Project.list()` currently return a simple `Object`, and an array of simple `Object`s respectively, as opposed to actual `Weaver.Project`s. This means that all `Weaver.Project` methods and functionality are unavailable, such as `destroy()`, `getACL()`, `set()` etc

**Comment by malamili** [comment]
Good one thnx! I'll pick this one up

**Comment by Gielert** [comment]
Is this one fixed in #91?

**Comment by Gielert** [comment]
Closing, fixed in #91
